version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: movie_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  movieplatformapi:
    image: ${DOCKER_REGISTRY-}movieplatformapi
    build:
      context: .
      dockerfile: MoviePlatformAPI/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
    ports:
      - "${API_PORT}:8080"
    volumes:
      - ./MoviePlatformAPI/wwwroot/uploads:/app/wwwroot/uploads

volumes:
  postgres_data: